config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'

  resources :books

  resources :users

  resource :homes, only: [:show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user

	validates :title, presence: true
	validates :opinion, presence: true
	validates :opinion, length: {maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  attachment :user_image

  validates :name, presence: true
  validates :name, length: {in: 2..20}
  validates :introduction, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name,  :password ])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  def index
  	@book = Book.new
  	@books = Book.all
  	@user = current_user
  end

  def create
  	@book = Book.new(book_params)
  	@book.user_id = current_user.id

    @books = Book.all
    @user = current_user
  	if @book.save
      flash[:success] = "successfully"
  	  redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  def show
  	@book = Book.new
  	@book_show = Book.find(params[:id])
    @user = @book_show.user
  end

  def edit
  	@book = Book.find(params[:id])
  end

  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
      flash[:success] = "successfully"
  	  redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
  	book = Book.find(params[:id])
  	book.destroy
  	redirect_to books_path
  end

private
  def book_params
  	params.require(:book).permit(:title, :opinion)
  end

  def user_params
    params.require(:user).permit(:name, :introduction, :user_image)
  end

  def correct_user
     book = Book.find(params[:id])
     # belong_toのおかげでnoteオブジェクトからuserオブジェクトへアクセスできる。
    if current_user.id != book.user.id
       redirect_to books_path
    end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  def top
  end

  def show
  	@book = Book.new
  	@user = User.find(params[:id])
  	@books = @user.books.page(params[:page]).reverse_order
  end

  def index
  	@book = Book.new
  	@user = current_user
  	@users = User.all
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "successfully"
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end



  private

    def user_params
      params.require(:user).permit(:name, :introduction, :user_image)
    end

    def correct_user
      user = User.find(params[:id])
      if current_user != user
        redirect_to books_path
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_user?(user)
    current_user.id == user.id
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-6 col-xs-offset-3">
            <h2>Editing Book</h2>

            <% if @book.errors.any? %>
                <div id="error_explanation" class="text-danger">
	                <h2><%= @book.errors.count %> error prohibited this obj from being saved:</h2>
	                <ul>
		                <% @book.errors.full_messages.each do |message| %>
		                <li><%= message %></li>
		                <% end %>
	                </ul>
                </div>
            <% end %>

            <%= form_for(@book) do |f| %>
                <div class="form-group">
                    <label>Title</label>
                    <br>
                    <%= f.text_field :title, :class=>"form-control book_title" %>
                </div>
                <div class="form-group">
                    <label>Opinion</label>
                    <br>
                    <%= f.text_area :opinion, :class=>"form-control book_body" %>
                </div>
                <div class="form-group">
                <%= f.submit "Update Book", :class=>"btn btn-primary btn-block book_#{@book.id}" %>
                </div>
            <% end %>

            <%= link_to "Show", book_path(@book.id), class: "book_#{@book.id}" %>
            |
            <%= link_to "Back", books_path, class: "back" %>
        </div>
    </div>
</div>

app/views/books/index.html.erb
<div class="container">

            <% if @book.errors.any? %>
                <div id="error_explanation" class="text-danger" >
                    <h2><%= @book.errors.count %> error prohibited this obj from being saved:</h2>
                    <ul>
                    <% @book.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                    </ul>
                </div>
            <% end %>

	<div class="row">
		<div class="col-xs-3">

			<h2>User info</h2>

            <%= attachment_image_tag @user, :user_image, :fill, 100, 100, fallback: "no_image.jpg", :size =>'100x100' %>

            <table class="table">
	            <tbody>
                    <tr>
			            <th>name</th>
                        <th><%= @user.name %></th>
		            </tr>
                    <tr>
			            <th>introduction</th>
                        <th><%= @user.introduction %></th>
		            </tr>
		        </tbody>
	        </table>

            <%= link_to edit_user_path(@user.id), class: "btn btn-default btn-block edit_user_#{@user.id}" do %>
            <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
            <% end %>

			<h2>New book</h2>
			<%= form_for(@book) do |f| %>

			<div class="form-group">
			<label>Title</label>
			<br>
			<%= f.text_field :title, :class=>"form-control book_title" %>
			</div>

			<div class="form-group">
			<label>Opinion</label>
			<br>
			<%= f.text_area :opinion, :class=>"form-control book_body" %>
			</div>

			<%= f.submit 'Create Book', :class=>"btn btn-primary btn-block" %>
			<% end %>
		</div>

		<div class="col-xs-9">
			<h2>Books</h2>
            <table class="table">
	            <thead>
		            <tr>
			            <th></th>
			            <th>Title</th>
			            <th>Opinion</th>
			            <th colspan="3"></th>
		            </tr>
	            </thead>

	            <tbody>
	                <% @books.each do |book| %>
		            <tr>
			            <td>
			            	<%= link_to user_path(book.user) do %>
			            	<%= attachment_image_tag book.user, :user_image, :fill, 60, 60, fallback: "no_image.jpg", :size =>'60x60' %>
			            	<% end %>
			            </td>
			            <td><%= link_to "#{book.title}", "#{book_path(book.id)}", :class=>"book_#{book.id}" %></td>
			            <td><%= book.opinion %></td>
		            </tr>
		            <% end %>
	            </tbody>
            </table>
        </div>
    </div>
</div>

app/views/books/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">

			<% if flash[:success] %>
                <p><%= flash[:success] %></p>
            <% end %>

			<h2>User info</h2>

            <%= attachment_image_tag @user, :user_image, :fill, 100, 100, fallback: "no_image.jpg", :size =>'100x100' %>

            <table class="table">
	            <tbody>
                    <tr>
			            <th>name</th>
                        <th><%= @user.name %></th>
		            </tr>
                    <tr>
			            <th>introduction</th>
                        <th><%= @user.introduction %></th>
		            </tr>
		        </tbody>
	        </table>

            <%= link_to edit_user_path(@user.id), class: "btn btn-default btn-block edit_user_#{@user.id}" do %>
            <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
            <% end %>

			<h2>New book</h2>
			<%= form_for(@book) do |f| %>

			<div class="form-group ">
			<label>Title</label>
			<br>
			<%= f.text_field :title, :class=>"form-control book_title" %>
			</div>

			<div class="form-group ">
			<label>Opinion</label>
			<br>
			<%= f.text_area :opinion, :class=>"form-control book_body" %>
			</div>

			<%= f.submit 'Create Book', :class=>"btn btn-primary btn-block" %>
			<% end %>
		</div>

		<div class="col-xs-9">
			<h2>Book detail</h2>
            <table class="table">

	            <tbody>
		            <tr>
			            <td>
			            	<%= link_to user_path(@user.id), class: "user_#{@user.id}" do %>
			            	<%= attachment_image_tag @user, :user_image, :fill, 100, 100, fallback: "no_image.jpg", :size =>'100x100' %>
			            	<br>
			            	<%= @user.name %>
			            	<% end %>
			            </td>
			            <td><%= @book_show.title %></td>
			            <td><%= @book_show.opinion %></td>
			            <% if @book_show.user == current_user %>
			                <td><%= link_to "Edit", edit_book_path(@book_show.id), class: "btn btn-success btn-sm edit_book_#{@book_show.id}" %></td>
			                <td><%= link_to "Destroy", book_path(@book_show.id), method: :delete, "data-confirm" => "Are you sure?", class: "btn btn-danger btn-sm destroy_book_#{@book_show.id}" %></td>
			            <% end %>
		            </tr>

	            </tbody>
            </table>
        </div>
    </div>
</div>

app/views/homes/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-1">
		</div>
        <h1>Welcome to
	    <span class="glyphicon glyphicon-book" aria-hidden="true"></span>
            Bookers !!
        </h1>
    </div>
</div>

app/views/homes/top.html.erb
<div class="container">
	<div class="row">

		<div class="col-xs-6 col-xs-offset-3">
            <h1>Welcome to
            <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers !!</h1>

            <p>In <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers,</p>
            <p>you can share and exchange your opinions , inpressions , and emotions</p>
            <p>about varioius books!</p>

            <div class="col-xs-10 col-xs-offset-1">
                <%= link_to "Log in", new_user_session_path, :class=>"btn btn-info btn-block sign_in" %>
            </div>

            <div class="col-xs-10 col-xs-offset-1">
                <%= link_to "Sign up", new_user_registration_path, :class=>"btn btn-success btn-block sign_up" %>
            </div>
        </div>

    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookersLevel2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="padding-top:51px;">
      <header>
          <nav class="navbar navbar-inverse navbar-fixed-top">
              <div class="container-fluid">
                  <div class="container">
                      <div class="navbar-header navbar-left">
                          <span class="header-title">Bookers</span>
                      </div>

                      <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">
                          <% if user_signed_in? %>
                          <li class="">
                              <%= link_to user_path(current_user.id), class: "home"  do %>
                                  <span class="glyphicon glyphicon-home home" aria-hidden="true"> Home</span>
                              <% end %>
                          </li>

                          <li class="">
                              <%= link_to users_path, class: 'users' do %>
                                  <span class="glyphicon glyphicon-user users" aria-hidden="true"> Users</span>
                              <% end %>
                          </li>

                          <li class="">
                              <%= link_to books_path, class: 'books' do %>
                                  <span class="glyphicon glyphicon-book books" aria-hidden="true"> Books</span>
                              <% end %>
                          </li>

                          <li class="">
                              <%= link_to destroy_user_session_path, method: :delete, class: 'logout' do %>
                                  <span class="glyphicon glyphicon-log-out logout" aria-hidden="true"> logout</span>
                              <% end %>
                          </li>

                          <% else %>
                          <li class="">
                              <%= link_to root_path, class: 'home' do %>
                                  <span class="glyphicon glyphicon-home home" aria-hidden="true"> Home</span>
                              <% end %>
                          </li>

                          <li class="">
                              <%= link_to homes_path, class: 'about' do %>
                                  <span class="glyphicon glyphicon-link about" aria-hidden="true"> About</span>
                              <% end %>
                          </li>

                          <li class="">
                              <%= link_to new_user_registration_path, class: 'sign_up' do %>
                                  <span class="glyphicon glyphicon-edit sign_up" aria-hidden="true"> sign up</span>
                              <% end %>
                          </li>

                          <li class="">
                              <%= link_to new_user_session_path, class: 'sign_in' do %>
                                  <span class="glyphicon glyphicon-log-in sign_in" aria-hidden="true"> login</span>
                              <% end %>
                          </li>
                          <% end %>
                      </ul>
                  </div>
              </div>
          </nav>
      </header>

      <%= yield %>

      <footer>
        <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
              <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
      </footer>

  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
    <h2>User info</h2>

<% if @user.errors.any? %>
    <div id="error_explanation" class="text-danger" >
      <h2><%= @user.errors.count %> error prohibited this obj from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= form_for(@user) do |f| %>
    <div class="form-group">
        <label>Name</label>
　      <%= f.text_field :name, class: "name" %>
    </div>

    <div class="form-group">
        <label>Image</label>
　      <%= f.file_field :user_image, class: "user_image" %>
    </div>

    <div class="form-group">
        <label>Introduction</label>
        <%= f.text_area :introduction, class: "introduction" %>
    </div>

    <%= f.submit "Update User" %>
    <% end %>
</div>

app/views/users/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<h2>User info</h2>

            <%= attachment_image_tag @user, :user_image, :fill, 100, 100, fallback: "no_image.jpg", :size =>'100x100' %>

            <table class="table">
	            <tbody>
                    <tr>
			            <th>name</th>
                        <th><%= @user.name %></th>
		            </tr>
                    <tr>
			            <th>introduction</th>
                        <th><%= @user.introduction %></th>
		            </tr>
		        </tbody>
	        </table>

            <%= link_to edit_user_path(@user.id), class: "btn btn-default btn-block edit_user_#{@user.id}" do %>
            <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
            <% end %>

			<h2>New book</h2>
			<%= form_for(@book) do |f| %>

			<div class="form-group">
			<label>Title</label>
			<br>
			<%= f.text_field :title, :class=>"form-control book_title" %>
			</div>

			<div class="form-group">
			<label>Opinion</label>
			<br>
			<%= f.text_area :opinion, :class=>"form-control book_body" %>
			</div>

			<%= f.submit 'Create Book', :class=>"btn btn-primary btn-block" %>
			<% end %>
		</div>

		<div class="col-xs-9">
			<h2>Users</h2>
            <table class="table">
	            <thead>
		            <tr>
			            <th>image</th>
			            <th>name</th>
			            <th colspan="3"></th>
		            </tr>
	            </thead>

	            <tbody>
	                <% @users.each do |user| %>
		            <tr>
			            <td><%= attachment_image_tag user, :user_image, :fill, 60, 60, fallback: "no_image.jpg", :size =>'60x60' %></td>
			            <td><%= user.name %></td>
			            <td><%= link_to "show", user_path(user.id), class: "user_#{user.id}" %> </td>
		            </tr>
		            <% end %>
	            </tbody>
            </table>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="container">
	<% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

	<div class="row">
		<div class="col-xs-3">


			<h2>User info</h2>

            <%= attachment_image_tag @user, :user_image, :fill, 100, 100, fallback: "no_image.jpg", :size =>'100x100' %>

            <table class="table">
	            <tbody>
                    <tr>
			            <th>name</th>
                        <th><%= @user.name %></th>
		            </tr>
                    <tr>
			            <th>introduction</th>
                        <th><%= @user.introduction %></th>
		            </tr>
		        </tbody>
	        </table>

	        <% if @user == current_user %>
                <%= link_to edit_user_path(@user.id), class: "btn btn-default btn-block edit_user_#{@user.id}" do %>
                <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
                <% end %>
            <% end %>

			<h2>New book</h2>
			<%= form_for(@book) do |f| %>

			<div class="form-group">
			<label>Title</label>
			<br>
			<%= f.text_field :title, :class=>"form-control book_title" %>
			</div>

			<div class="form-group">
			<label>Opinion</label>
			<br>
			<%= f.text_area :opinion, :class=>"form-control book_body" %>
			</div>

			<%= f.submit 'Create Book', :class=>"btn btn-primary btn-block" %>
			<% end %>
		</div>

		<div class="col-xs-9">
			<h2>Books</h2>
            <table class="table">
	            <thead>
		            <tr>
			            <th></th>
			            <th>Title</th>
			            <th>Opinion</th>
			            <th colspan="3"></th>
		            </tr>
	            </thead>

	            <tbody>
	                <% @books.each do |book| %>
		            <tr>
			            <td><%= attachment_image_tag book.user, :user_image, :fill, 60, 60, fallback: "no_image.jpg", :size =>'60x60' %></td>
			            <td><%= link_to "#{book.title}", "#{book_path(book.id)}", class: "book_#{book.id}" %></td>
			            <td><%= book.opinion %></td>
			            <td></td>
		            </tr>
		            <% end %>
	            </tbody>
            </table>
        </div>
    </div>
</div>